import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * PluginInfoCard: 「设置 → 插件信息」卡——图标 + 插件名/版本 tag + 描述，下接
 * 元信息网格（作者 / 仓库 / npm / 许可证）。版本号来自服务端 usage-stats 的
 * `pluginVersion`（读自包 package.json），其余元信息静态来自 `plugin-info.ts`。
 * 无版本号时显示 em dash。
 */
import css from './UsageBilling.module.css';
import { PLUGIN_AUTHOR_HANDLE, PLUGIN_AUTHOR_NAME, PLUGIN_DESCRIPTION, PLUGIN_LICENSE, PLUGIN_NAME, PLUGIN_NPM_URL, PLUGIN_REPOSITORY, } from "./plugin-info.js";
/** 信息卡 props：locale 函数 + 版本号（服务端下发，可为空）。 */
export function PluginInfoCard({ t, version }) {
    return (_jsxs("section", { className: css.setCard, "data-testid": "billing-plugin-info", children: [_jsxs("div", { className: css.plgHead, children: [_jsx("span", { className: css.plgIcon, "aria-hidden": "true", children: _jsx("svg", { width: "20", height: "20", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: _jsx("path", { d: "M10 3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a2 2 0 0 0 4 0V4a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a2 2 0 0 0 4 0 1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1a2 2 0 0 0 0 4h1a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1a2 2 0 0 0-4 0v1a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2a2 2 0 0 0-4 0v1a1 1 0 0 1-1 1h-1a1 1 0 0 1-1-1v-1a2 2 0 0 0-4 0 1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1h1a2 2 0 0 0 0-4H3a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1h1a2 2 0 0 0 4 0z" }) }) }), _jsxs("div", { className: css.plgTitle, children: [_jsxs("div", { className: css.plgNameRow, children: [_jsx("h3", { className: css.plgName, children: PLUGIN_NAME }), _jsx("span", { className: css.plgTag, children: version === undefined ? '—' : `v${version}` })] }), _jsx("p", { className: css.plgDesc, children: PLUGIN_DESCRIPTION })] })] }), _jsxs("div", { className: css.plgGrid, children: [_jsxs("div", { className: css.plgItem, children: [_jsx("span", { className: css.plgLabel, children: t('billing.pluginAuthor') }), _jsxs("a", { className: css.plgLink, href: `https://github.com/${PLUGIN_AUTHOR_HANDLE}`, target: "_blank", rel: "noreferrer", children: [PLUGIN_AUTHOR_NAME, " (", PLUGIN_AUTHOR_HANDLE, ")"] })] }), _jsxs("div", { className: css.plgItem, children: [_jsx("span", { className: css.plgLabel, children: t('billing.pluginRepository') }), _jsx("a", { className: css.plgLink, href: PLUGIN_REPOSITORY, target: "_blank", rel: "noreferrer", children: "GitHub" })] }), _jsxs("div", { className: css.plgItem, children: [_jsx("span", { className: css.plgLabel, children: t('billing.pluginNpm') }), _jsx("a", { className: css.plgLink, href: PLUGIN_NPM_URL, target: "_blank", rel: "noreferrer", children: PLUGIN_NAME })] }), _jsxs("div", { className: css.plgItem, children: [_jsx("span", { className: css.plgLabel, children: t('billing.pluginLicense') }), _jsx("span", { className: css.plgVal, children: PLUGIN_LICENSE })] })] })] }));
}
//# sourceMappingURL=PluginInfoCard.js.map