import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * PluginInfoCard: 「设置 → 插件信息」卡——展示头像/作者、GitHub 仓库、版本号、
 * 许可证等插件元信息。版本号来自服务端 usage-stats 的 `pluginVersion`（读自
 * 包 package.json），其余元信息静态来自 `plugin-info.ts`。无版本号时显示 em dash。
 */
import css from './UsageBilling.module.css';
import { PLUGIN_AUTHOR_HANDLE, PLUGIN_AUTHOR_NAME, PLUGIN_DESCRIPTION, PLUGIN_LICENSE, PLUGIN_NAME, PLUGIN_NPM_URL, PLUGIN_REPOSITORY, } from "./plugin-info.js";
/** 信息卡 props：locale 函数 + 版本号（服务端下发，可为空）。 */
export function PluginInfoCard({ t, version }) {
    return (_jsxs("section", { className: css.panel, "data-testid": "billing-plugin-info", children: [_jsx("div", { className: css.panelHead, children: _jsx("h3", { className: css.panelTitle, children: t('billing.pluginInfo') }) }), _jsxs("div", { className: css.pluginInfo, children: [_jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginName') }), _jsx("span", { className: css.pluginInfoValue, children: PLUGIN_NAME })] }), _jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginDescription') }), _jsx("span", { className: css.pluginInfoValue, children: PLUGIN_DESCRIPTION })] }), _jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginVersion') }), _jsx("span", { className: css.pluginInfoValue, children: version === undefined ? '—' : `v${version}` })] }), _jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginAuthor') }), _jsxs("a", { className: css.pluginInfoLink, href: `https://github.com/${PLUGIN_AUTHOR_HANDLE}`, target: "_blank", rel: "noreferrer", children: [PLUGIN_AUTHOR_NAME, " (", PLUGIN_AUTHOR_HANDLE, ")"] })] }), _jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginRepository') }), _jsx("a", { className: css.pluginInfoLink, href: PLUGIN_REPOSITORY, target: "_blank", rel: "noreferrer", children: PLUGIN_REPOSITORY })] }), _jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginNpm') }), _jsx("a", { className: css.pluginInfoLink, href: PLUGIN_NPM_URL, target: "_blank", rel: "noreferrer", children: PLUGIN_NAME })] }), _jsxs("div", { className: css.pluginInfoRow, children: [_jsx("span", { className: css.pluginInfoLabel, children: t('billing.pluginLicense') }), _jsx("span", { className: css.pluginInfoValue, children: PLUGIN_LICENSE })] })] })] }));
}
//# sourceMappingURL=PluginInfoCard.js.map